import * as data from './bunkerData';

/** Two-story bunker — original map */
const bunker = {
  id: 'bunker',
  name: 'Bunker',
  blurb: 'Hold the concrete shell. Classic single-floor layout.',
  worldBound: 13.5,
  theme: 'stone',
  WALL_THICKNESS: data.WALL_THICKNESS,
  WALL_HEIGHT: data.WALL_HEIGHT,
  FLOOR_Y: data.FLOOR_Y,
  WALLS: data.WALLS,
  ROOMS: data.ROOMS,
  DOORS: data.DOORS,
  WINDOWS: data.WINDOWS,
  WALLBUYS: data.WALLBUYS,
  SPAWN_POINTS: data.SPAWN_POINTS,
  PLAYER_SPAWN: data.PLAYER_SPAWN,
  FLOORS: data.FLOORS,
  LIGHTS: data.LIGHTS,
  MYSTERY_BOX: {
    position: [0, 0, 0.5],
    rotation: [0, 0, 0],
    room: 'spawn',
  },
  MYSTERY_BOX_SPOTS: [
    { position: [0, 0, 0.5], rotation: [0, 0, 0], room: 'spawn' },
    { position: [-3.5, 0, -9], rotation: [0, 0.4, 0], room: 'spawn' },
    { position: [-11, 0, 2], rotation: [0, Math.PI / 2, 0], room: 'west' },
    { position: [11, 0, 2], rotation: [0, -Math.PI / 2, 0], room: 'east' },
    { position: [0, 0, 11], rotation: [0, Math.PI, 0], room: 'north' },
  ],
  props: [
    { type: 'crate', position: [3.2, 0.42, -8] },
    { type: 'crate', position: [3.2, 1.27, -8], color: 'wood' },
    { type: 'crate', position: [-3.8, 0.42, -7.2], color: 'wood' },
    { type: 'crate', position: [4.5, 0.42, -10], color: 'plankDark' },
    { type: 'sandbags', position: [5.5, 0, -11], yaw: 0.2, count: 3 },
    { type: 'ammoCrate', position: [-6, 0, -10.5], yaw: -0.3 },
    { type: 'cone', position: [2, 0, -5] },
    { type: 'cone', position: [-2.5, 0, -4.5] },
    { type: 'ammoCrate', position: [1.2, 0, -7.5], yaw: 0.4 },
    { type: 'rubble', position: [-4.5, 0, -11.5] },
    { type: 'rubble', position: [6, 0, -8.5] },
    { type: 'rubble', position: [-5.5, 0, -6] },
    { type: 'crate', position: [0, 0.42, 11.5], color: 'plankDark' },
    { type: 'crate', position: [0, 1.27, 11.5], color: 'wood' },
    { type: 'platform', position: [5.2, 1.72, -9.5], size: [1.4, 0.16, 1.1] },
    { type: 'platform', position: [6.4, 2.45, -8.2], size: [1.3, 0.16, 1.0] },
    { type: 'sandbags', position: [-9.5, 0, 5], yaw: Math.PI / 2, count: 3 },
    { type: 'sandbags', position: [9.5, 0, 5], yaw: Math.PI / 2, count: 3 },
    { type: 'ammoCrate', position: [-10.5, 0, 9], yaw: 0.5 },
    { type: 'cone', position: [-10, 0, -0.5] },
    { type: 'cone', position: [10, 0, -0.5] },
    { type: 'rubble', position: [0, 0, 7] },
    { type: 'dumpster', position: [-11.5, 0, -2], yaw: Math.PI / 2 },
    { type: 'rubble', position: [3, 0, 10] },
    { type: 'ammoCrate', position: [-2.5, 0, -10], yaw: 0.25 },
    { type: 'crate', position: [-10.5, 0.42, 1.5], color: 'wood' },
    { type: 'crate', position: [10.5, 0.42, 1.5], color: 'plankDark' },
    { type: 'crate', position: [4.2, 0.42, 8], color: 'wood' },
    { type: 'sandbags', position: [0, 0, 5.5], count: 2 },
    { type: 'hangingBulb', position: [0, 3.4, -9], intensity: 1.2 },
    { type: 'hangingBulb', position: [-10, 3.4, 2], intensity: 0.85 },
    { type: 'hangingBulb', position: [10, 3.4, 2], intensity: 0.85 },
    { type: 'hangingBulb', position: [0, 3.4, 9], intensity: 1.0, color: '#c85828' },
  ],
};

export default bunker;
